=== solargis/schemas/v1/solargis_public_TMY_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/main/v1/solargis_public_TMY_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for Solargis data request - for TMY datasets.",
  "required": [
    "requestType",
    "site",
    "timeStep",
    "fromDate",
    "toDate",
    "tmyScenario",
    "columns",
    "outputFormat"
  ],
  "properties": {
    "requestType": {
      "const": "TMY"
    },
    "site": {
      "description": "Site location definition.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/site"
    },
    "timeStep": {
      "enum": [
        "PT15M",
        "PT30M",
        "PT60M"
      ]
    },
    "fromDate": {
      "description": "Start date of the requested data. Inclusive.",
      "const": "AUTODETECT"
    },
    "toDate": {
      "description": "End date of the requested data. Inclusive.",
      "const": "LAST_YEAR"
    },
    "columns": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/columns"
    },
    "tmyScenario": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/tmyScenario"
    },
    "utcOffset": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/utcOffset"
    },
    "timeAlignment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/timeAlignment"
    },
    "terrainShading": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/terrainShading"
    },
    "horizon": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/horizon"
    },
    "groundAlbedo": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/groundAlbedo"
    },
    "gtiConfiguration": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/gtiConfiguration"
    },
    "fileLabel": {
      "$ref": "solargis_common_types.schema.json#/$defs/FileLabel"
    },
    "outputFormat": {
      "enum": [
        "SOLARGIS_JSON"
      ]
    },
    "compressOutput": {
      "description": "Output dataset will be zipped.",
      "type": "boolean",
      "default": false
    },
    "stochasticGenerator": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/stochasticGenerator"
    }
  }
}

=== solargis/schemas/v1.0/examples/requests/public/tmy/tmy_request_mini.json
{
  "$schema": "https://raw.githubusercontent.com/solargis/schemas/main/v1.0/solargis_public_TMY_request.schema.json",
  "requestType": "TMY",
  "site": {
    "latitude": 45.09,
    "longitude": 17.34
  },
  "timeStep": "PT15M",
  "columns": [
    "GHI"
  ],
  "tmyScenario": "P50",
  "fromDate": "AUTODETECT",
  "toDate": "LAST_YEAR",
  "stochasticGenerator": false,
  "outputFormat": "SOLARGIS_JSON",
  "compressOutput": false
}
