=== solargis/schemas/v1/solargis_public_TS_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/v1.0.1/v1/solargis_public_TS_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for Solargis data request - for timeseries datasets.",
  "required": [
    "site",
    "timeStep",
    "fromDate",
    "toDate",
    "columns",
    "outputFormat"
  ],
  "additionalProperties": true,
  "properties": {
    "site": {
      "description": "Site location definition.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/site"
    },
    "timeStep": {
      "enum": [
        "PT15M",
        "PT30M",
        "PT60M",
        "P1D",
        "P1M",
        "P1Y"
      ]
    },
    "fromDate": {
      "description": "Start date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/fromDate"
    },
    "toDate": {
      "description": "End date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/toDate"
    },
    "columns": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/columns"
    },
    "utcOffset": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/utcOffset"
    },
    "timeAlignment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/timeAlignment"
    },
    "terrainShading": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/terrainShading"
    },
    "horizon": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/horizon"
    },
    "surfaceAlbedo": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/surfaceAlbedo"
    },
    "gtiConfiguration": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/gtiConfiguration"
    },
    "fileLabel": {
      "$ref": "solargis_common_types.schema.json#/$defs/FileLabel"
    },
    "outputFormat": {
      "enum": [
        "SOLARGIS_JSON"
      ]
    },
    "compressOutput": {
      "description": "Output dataset will be zipped.",
      "type": "boolean",
      "default": false
    },
    "stochasticGenerator": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/stochasticGenerator"
    }
  }
}

=== solargis/schemas/v1/examples/requests/public/ts/ts_request_gti_OneAxisInclinedTrackerNs.json
{
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District",
    "countryName": "Japan",
    "countryISOCode": "JP",
    "id": "AX_987JP"
  },
  "timeStep": "PT15M",
  "columns": [
    "GHI",
    "DIF",
    "DNI",
    "GTI"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": "+09:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "fileLabel": "Pippu_AX_987JP",
  "horizon": {
    "azimuth": [
      0.0,
      360
    ],
    "height": [
      19.0581,
      31.2
    ]
  },
  "surfaceAlbedo": 0.12,
  "gtiConfiguration": {
    "layout": {
      "azimuth": 180,
      "relativeSpacing": 2.5,
      "mounting": {
        "type": "ONE_AXIS_INCLINED_TRACKER_NS",
        "axisTilt": 30,
        "backtracking": false,
        "rotationLimitEast": -50,
        "rotationLimitWest": 50
      }
    },
    "environment": {
      "terrainAlbedo": [
        0.23,
        0.20,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.15
      ],
      "horizon": {
        "azimuth": [
          0.0,
          360
        ],
        "height": [
          30,
          51.2
        ]
      }
    }
  },
  "outputFormat": "SOLARGIS_JSON",
  "stochasticGenerator": false,
  "compressOutput": false
}
