=== solargis/schemas/solargis_public_TS_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/v1.1.1/solargis_public_TS_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for Solargis data request - for timeseries datasets.",
  "type": "object",
  "required": [
    "site",
    "timeStep",
    "fromDate",
    "toDate",
    "columns",
    "outputFormat"
  ],
  "additionalProperties": true,
  "properties": {
    "site": {
      "description": "Site location definition.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/site"
    },
    "timeStep": {
      "type": "string",
      "enum": [
        "PT15M",
        "PT30M",
        "PT60M",
        "P1D",
        "P1M",
        "P1Y"
      ]
    },
    "fromDate": {
      "description": "Start date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/fromDate"
    },
    "toDate": {
      "description": "End date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/toDate"
    },
    "columns": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/columns"
    },
    "utcOffset": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/utcOffset"
    },
    "timeAlignment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/timeAlignment"
    },
    "terrainShading": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/terrainShading"
    },
    "environment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/environment"
    },
    "gtiConfiguration": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/gtiConfiguration"
    },
    "fileLabel": {
      "$ref": "solargis_common_types.schema.json#/$defs/FileLabel"
    },
    "outputFormat": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/outputFormat"
    },
    "compressOutput": {
      "description": "Output dataset will be zipped.",
      "type": "boolean",
      "default": false
    },
    "stochasticGenerator": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/stochasticGenerator"
    }
  }
}

=== solargis/schemas/examples/requests/public/ts/ts_request_integration_basic.json
{
  "site": {
    "latitude": 48.61259,
    "longitude": 20.827079,
    "siteName": "Basic example Site"
  },
  "timeStep": "PT60M",
  "columns": [
    "GHI",
    "DNI",
    "DIF",
    "SUN_ELEVATION",
    "SUN_AZIMUTH",
    "TEMP",
    "WS",
    "WD"
  ],
  "fromDate": "1994-01-01",
  "toDate": "2022-12-31",
  "utcOffset": "+01:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "outputFormat": "SOLARGIS_JSON",
  "fileLabel": "basic_01"
}

=== solargis/schemas/examples/requests/public/ts/ts_request_gti_TrackerTwoAxis.json
{
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District",
    "countryName": "Japan",
    "countryISOCode": "JP",
    "id": "AX_987JP"
  },
  "timeStep": "PT15M",
  "columns": [
    "CI_FLAG",
    "DIF",
    "DIF_NOSHD",
    "DNI",
    "DNI_C",
    "DNI_NOSHD",
    "GHI",
    "GHI_C",
    "GHI_NOSHD",
    "GTI",
    "GTI_C",
    "GTI_NOSHD",
    "KC",
    "SUN_AZIMUTH",
    "SUN_ELEVATION"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": "+09:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "fileLabel": "Pippu_AX_987JP",
  "environment": {
    "surfaceAlbedo": 0.12,
    "horizon": {
      "azimuth": [
        0.0,
        360
      ],
      "height": [
        19.0581,
        31.2
      ]
    }
  },
  "gtiConfiguration": {
    "layout": {
      "azimuth": 180,
      "relativeSpacing": 2.5,
      "mounting": {
        "type": "TRACKER_TWO_AXIS",
        "backtracking": true,
        "tiltLimitMin": 10,
        "tiltLimitMax": 90,
        "azimuthLimitEast": -90,
        "azimuthLimitWest": 90
      }
    },
    "environment": {
      "surfaceAlbedo": [
        0.23,
        0.20,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.15
      ],
      "horizon": {
        "azimuth": [
          0.0,
          360
        ],
        "height": [
          30,
          51.2
        ]
      }
    }
  },
  "outputFormat": "SOLARGIS_JSON",
  "stochasticGenerator": false,
  "compressOutput": false
}

=== solargis/schemas/examples/requests/public/ts/ts_request_gti_FixedOneAngleSeasonal.json
{
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District",
    "countryName": "Japan",
    "countryISOCode": "JP"
  },
  "timeStep": "PT15M",
  "columns": [
    "CI_FLAG",
    "DIF",
    "DIF_NOSHD",
    "DNI",
    "DNI_NOSHD",
    "GHI",
    "GHI_C",
    "GHI_NOSHD",
    "GTI",
    "GTI_C",
    "GTI_CIRC",
    "GTI_CIRC_NOSHD",
    "GTI_DIR",
    "GTI_DIR_NOSHD",
    "GTI_ISO_HOR",
    "GTI_ISO_HOR_NOSHD",
    "GTI_NOSHD",
    "GTI_REFL",
    "GTI_REFL_NOSHD",
    "GTI_UNC_HIGH",
    "GTI_UNC_LOW",
    "PANEL_AZIMUTH",
    "PANEL_INC",
    "PANEL_TILT",
    "SUN_AZIMUTH",
    "SUN_ELEVATION"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": "+09:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "fileLabel": "Pippu_AX_987JP",
  "environment": {
    "surfaceAlbedo": 0.12,
    "horizon": {
      "azimuth": [
        0,
        37.5,
        60,
        82.5,
        105,
        127.5,
        150,
        172.5,
        195,
        217.5,
        240,
        262.5,
        285,
        307.5,
        330,
        352.5
      ],
      "height": [
        0.705,
        1.0588235,
        1.058894,
        1.428,
        0.70588764,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "gtiConfiguration": {
    "layout": {
      "azimuth": 180,
      "mounting": {
        "type": "FIXED_ONE_ANGLE_SEASONAL",
        "tilt": [
          {
            "dateOfChange": "03-21",
            "tilt": 30
          },
          {
            "dateOfChange": "09-21",
            "tilt": 50
          }
        ]
      }
    }
  },
  "outputFormat": "SOLARGIS_JSON",
  "stochasticGenerator": false,
  "compressOutput": false
}
