=== solargis/schemas/solargis_public_TS_API_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/v1.1.1/solargis_public_TS_API_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for Solargis data request - for getting timeseries datasets via API.",
  "type": "object",
  "required": [
    "site",
    "timeStep",
    "fromDate",
    "toDate",
    "columns",
    "outputFormat"
  ],
  "additionalProperties": true,
  "properties": {
    "site": {
      "description": "Site location definition.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/site",
      "examples": [
        {
          "latitude": 43.913961,
          "longitude": 142.419596,
          "elevation": 179,
          "name": "Pippu 比布町, Kamikawa District, Japan"
        }
      ]
    },
    "timeStep": {
      "enum": [
        "PT1M",
        "PT5M",
        "PT10M",
        "PT15M",
        "PT60M",
        "P1D",
        "P1M",
        "P1Y"
      ]
    },
    "fromDate": {
      "description": "Start date of the requested data. Inclusive. See also the utcOffset.",
      "oneOf": [
        {
          "type": "string",
          "format": "date"
        },
        {
          "const": "AUTODETECT"
        }
      ]
    },
    "toDate": {
      "description": "End date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/toDate"
    },
    "columns": {
      "description": "Any valid column name is possible, but success output is generated only if name is allowed in the API subscription.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/columns"
    },
    "utcOffset": {
      "description": "ISO 8601 time zone designator (offset from UTC) formatted as ±hh:mm. Allows only whole hour or half-hour offsets in the range ±14:30. If this property is missing the UTC is used (00:00).",
      "type": "string",
      "pattern": "^([+\\\\-])?(0[0-9]|1[0-4]):(00|30)$",
      "examples": [
        "+05:30", "-07:00", "02:00"
      ]
    },
    "timeAlignment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/timeAlignment"
    },
    "terrainShading": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/terrainShading"
    },
    "environment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/environment"
    },
    "gtiConfiguration": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/gtiConfiguration"
    },
    "fileLabel": {
      "description": "The value will be used in the generated file name for output dataset.",
      "$ref": "solargis_common_types.schema.json#/$defs/FileLabel"
    },
    "outputFormat": {
      "enum": [
        "SOLARGIS_JSON", "SOLARGIS_CSV"
      ]
    },
    "compressOutput": {
      "description": "Output dataset file will be zipped.",
      "type": "boolean",
      "default": false
    },
    "includeSurfaceAlbedoLongTerm": {
      "description": "Include long-term average of surface albedo in the output dataset. The value is taken from the user request (if value is present) or from the Solargis database (if not provided by user). Only for SOLARGIS_JSON format.",
      "type": "boolean",
      "default": false
    },
    "includeHorizon": {
      "description": "Include horizon object in the output dataset (used for shading). The value is taken from the user request (if value is present) or from the Solargis database (if not provided by user). Only for SOLARGIS_JSON format.",
      "type": "boolean",
      "default": false
    }
  }
}

=== solargis/schemas/examples/requests/public/ts_api/ts_api_request_gti_TrackerTwoAxis.json
{
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District"
  },
  "timeStep": "PT15M",
  "columns": [
    "CI_FLAG",
    "DIF",
    "DNI",
    "GHI",
    "GHI_NOSHD",
    "GTI",
    "PANEL_AZIMUTH",
    "PANEL_INC",
    "PANEL_TILT",
    "SUN_AZIMUTH",
    "SUN_ELEVATION"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": "+09:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "environment": {
    "surfaceAlbedo": 0.12,
    "horizon": {
      "azimuth": [
        0,
        37.5,
        60,
        82.5,
        105,
        127.5,
        150,
        172.5,
        195,
        217.5,
        240,
        262.5,
        285,
        307.5,
        330,
        352.5
      ],
      "height": [
        0.705,
        1.0588235,
        1.058894,
        1.428,
        0.70588764,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "outputFormat": "SOLARGIS_JSON",
  "compressOutput": false,
  "includeSurfaceAlbedoLongTerm": true,
  "includeHorizon": true,
  "fileLabel": "Pippu_AX_987JP",
  "gtiConfiguration": {
    "layout": {
      "relativeSpacing": 2.5,
      "mounting": {
        "type": "TRACKER_TWO_AXIS",
        "backtracking": true,
        "tiltLimitMin": 10,
        "tiltLimitMax": 90,
        "azimuthLimitEast": -90,
        "azimuthLimitWest": 90
      }
    }
  }
}
