=== solargis/schemas/v1.0/solargis_public_TS_request.schema.json
{
  "$id": "https://raw.githubusercontent.com/solargis/schemas/main/v1.0/solargis_public_TS_request.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema",

  "description": "Schema for Solargis data request - for timeseries datasets.",
  "required": [
    "requestType",
    "site",
    "timeStep",
    "fromDate",
    "toDate",
    "columns",
    "outputFormat"
  ],
  "additionalProperties": true,
  "properties": {
    "requestType": {
      "const": "TIMESERIES"
    },
    "site": {
      "description": "Site location definition.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/site"
    },
    "timeStep": {
      "enum": [
        "PT15M",
        "PT30M",
        "PT60M",
        "P1D",
        "P1M",
        "P1Y"
      ]
    },
    "fromDate": {
      "description": "Start date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/fromDate"
    },
    "toDate": {
      "description": "End date of the requested data. Inclusive.",
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/toDate"
    },
    "columns": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/columns"
    },
    "utcOffset": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/utcOffset"
    },
    "timeAlignment": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/timeAlignment"
    },
    "terrainShading": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/terrainShading"
    },
    "horizon": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/horizon"
    },
    "groundAlbedo": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/groundAlbedo"
    },
    "gtiConfiguration": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/gtiConfiguration"
    },
    "fileLabel": {
      "$ref": "solargis_common_types.schema.json#/$defs/FileLabel"
    },
    "outputFormat": {
      "enum": [
        "SOLARGIS_JSON"
      ]
    },
    "compressOutput": {
      "description": "Output dataset will be zipped.",
      "type": "boolean",
      "default": false
    },
    "stochasticGenerator": {
      "$ref": "solargis_data_request.schema.json#/$defs/DataRequest/properties/stochasticGenerator"
    }
  }
}

=== solargis/schemas/v1.0/examples/requests/public/ts/ts_request_gti_OneAxisVerticalTracker.json
{
  "$schema": "https://raw.githubusercontent.com/solargis/schemas/main/v1.0/solargis_public_TS_request.schema.json",
  "requestType": "TIMESERIES",
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District",
    "countryName": "Japan",
    "countryISOCode": "JP",
    "id": "AX_987JP"
  },
  "timeStep": "PT15M",
  "columns": [
    "GHI",
    "DIF",
    "DNI",
    "GTI",
    "GTI_NOSHD"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": 9,
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "fileLabel": "Pippu_AX_987JP",
  "horizon": {
    "azimuth": [
      0.0,
      360
    ],
    "height": [
      19.0581,
      31.2
    ]
  },
  "groundAlbedo": 0.12,
  "gtiConfiguration": {
    "layout": {
      "azimuth": 180,
      "mounting": {
        "type": "ONE_AXIS_VERTICAL_TRACKER",
        "tilt": 30,
        "rotationLimitEast": -90,
        "rotationLimitWest": 90
      }
    },
    "environment": {
      "terrainAlbedo": [
        0.23,
        0.20,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.15
      ],
      "horizon": {
        "azimuth": [
          0.0,
          360
        ],
        "height": [
          30,
          51.2
        ]
      }
    }
  },
  "outputFormat": "SOLARGIS_JSON",
  "stochasticGenerator": false,
  "compressOutput": false
}

=== solargis/schemas/v1.0/examples/requests/public/ts/ts_request_mini.json
{
  "$schema": "https://raw.githubusercontent.com/solargis/schemas/main/v1.0/solargis_public_TS_request.schema.json",
  "requestType": "TIMESERIES",
  "site": {
    "latitude": 45.09,
    "longitude": 17.34
  },
  "timeStep": "PT15M",
  "columns": [
    "GHI"
  ],
  "fileLabel": "hjsb",
  "fromDate": "1992-09-09",
  "toDate": "LAST_MONTH",

  "outputFormat": "SOLARGIS_JSON",
  "compressOutput": true
}

=== solargis/schemas/v1/examples/requests/public/ts/ts_request_maxi.json
{
  "$schema": "https://raw.githubusercontent.com/solargis/schemas/main/v1/solargis_public_TS_request.schema.json",
  "requestType": "TIMESERIES",
  "site": {
    "latitude": 43.023903,
    "longitude": 142.419596,
    "elevation": 156.9,
    "name": "Pippu 比布町, Kamikawa District",
    "countryName": "Japan",
    "countryISOCode": "JP",
    "id": "AX_987JP"
  },
  "timeStep": "PT15M",
  "columns": [
    "GHI",
    "DIF",
    "DNI",
    "GTI",
    "GTI_NOSHD",
    "TEMP",
    "WS",
    "WS78"
  ],
  "fromDate": "2022-10-01",
  "toDate": "2022-10-02",
  "utcOffset": "+09:00",
  "timeAlignment": "CENTER",
  "terrainShading": true,
  "groundAlbedo": 0.12,
  "horizon": {
    "azimuth": [
      0.0,
      360
    ],
    "height": [
      19.0581,
      31.2
    ]
  },
  "gtiConfiguration": {
    "layout": {
      "azimuth": 180,
      "mounting": {
        "type": "FIXED_ONE_ANGLE",
        "tilt": 39
      }
    },
    "environment": {
      "terrainAlbedo": [
        0.23,
        0.20,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.12,
        0.15
      ],
      "horizon": {
        "azimuth": [
          0.0,
          360
        ],
        "height": [
          30,
          51.2
        ]
      }
    }
  },
  "stochasticGenerator": false,
  "outputFormat": "SOLARGIS_JSON",
  "fileLabel": "Pippu_AX_987JP",
  "compressOutput": true
}
